# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
remote_theme: ngzhio/jekyll-theme-hamilton
title: 49th LunaSea
email: fortneu@stu.pku.edu.cn
description: >- # this means to ignore newlines until "baseurl:"
  Cats are dangerous. è‡ªç”±è€Œæ²¡æœ‰å½’å®¿ã€‚
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: ""
github_username:  maki49

author: Fortneu49
copyright: " <a href='https://creativecommons.org/licenses/by/4.0/'>CC BY 4.0</a>"

# Build settings

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-remote-theme
  - jekyll-paginate

skin: midnight
avatar: avatar.jpg
subscribe: false
music: true
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

paginate: 4 
paginate_path: "/page:num/"

# Comments
comments:
  provider: utterances

utterances:
  repo: "maki49/maki49.github.io"
  issue-term: "pathname"
  label: "ðŸ’¬comment"
  theme: "icy-dark"  # more beautiful than dark-blue I think
